/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import javax.swing.JOptionPane;

/**
 *
 * @author Josué Vásquez
 */
public class SueldoEmpleados extends javax.swing.JFrame {
int total,bono=0,horae=0,otrob=0;
    /**
     * Creates new form SueldoEmpleados
     */
    public SueldoEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textNombre = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textDireccion = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textSueldo = new javax.swing.JTextPane();
        checkBono = new javax.swing.JCheckBox();
        checkHExtra = new javax.swing.JCheckBox();
        checkOBono = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        textTotal = new javax.swing.JTextPane();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("CALCULADORA DE SUELDO DE EMPLEADOS");

        jLabel2.setText("NOMBRE:");

        jScrollPane1.setViewportView(textNombre);

        jLabel3.setText("DIRECCIÓN:");

        jScrollPane2.setViewportView(textDireccion);

        jLabel4.setText("SUELDO BASE:");

        textSueldo.setEditable(false);
        jScrollPane3.setViewportView(textSueldo);

        checkBono.setText("Bono");
        checkBono.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBonoItemStateChanged(evt);
            }
        });
        checkBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBonoActionPerformed(evt);
            }
        });

        checkHExtra.setText("Horas Extra");
        checkHExtra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkHExtraItemStateChanged(evt);
            }
        });

        checkOBono.setText("Otros Bonos");
        checkOBono.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkOBonoItemStateChanged(evt);
            }
        });

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textTotal.setEditable(false);
        jScrollPane4.setViewportView(textTotal);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opción", "Administrador", "Jefe Sistemas", "Auditor", "Otro" }));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBono)
                            .addComponent(checkHExtra)
                            .addComponent(checkOBono)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBono))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkHExtra))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(checkOBono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        float Sueldo;
        
        
            String itemS = (String)combo.getSelectedItem();
            if("Administrador".equals(itemS))
            {
                Sueldo = (float)7000.00;
                total = (int)(Sueldo+bono+horae+otrob);
                textTotal.setText(String.valueOf(total));
            }
            else if("Jefe Sistemas".equals(itemS))
            {
                Sueldo = (float)1500.00;
                total = (int)(Sueldo+bono+horae+otrob);
                textTotal.setText(String.valueOf(total));
            }
            else if("Auditor".equals(itemS))
            {
                Sueldo = (float)9000.00;
                total = (int)(Sueldo+bono+horae+otrob);
                textTotal.setText(String.valueOf(total));
            }
            else if("Otro".equals(itemS))
            {
                Sueldo = (float)5000.00;
                total = (int)(Sueldo+bono+horae+otrob);
                textTotal.setText(String.valueOf(total));
            }
            else if("Elija una opción".equals(itemS))
            {
                JOptionPane.showMessageDialog(null, "Elija una opcion valida");
            }
      
        
        
        
            
        /*
            Elija una opción
            Administrador
            Jefe Sistemas
            Auditor
            Otro 
            */    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBonoActionPerformed

    private void checkBonoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBonoItemStateChanged
        // TODO add your handling code here:
        if(checkBono.isSelected())
            bono=250;
        else
            bono=0;
    }//GEN-LAST:event_checkBonoItemStateChanged

    private void checkHExtraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkHExtraItemStateChanged
        // TODO add your handling code here:
        if(checkHExtra.isSelected())
            horae=800;
        else
            horae=0;
    }//GEN-LAST:event_checkHExtraItemStateChanged

    private void checkOBonoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkOBonoItemStateChanged
        // TODO add your handling code here:
        if(checkOBono.isSelected())
            otrob=500;
        else
            otrob=0;
    }//GEN-LAST:event_checkOBonoItemStateChanged

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        // TODO add your handling code here:
        
        String itemS = (String)combo.getSelectedItem();
        int S;    
            if("Administrador".equals(itemS))
            {
                S = 7000;
                textSueldo.setText(String.valueOf(S));
            }
            else if("Jefe Sistemas".equals(itemS))
            {
                S = 1500;
                textSueldo.setText(String.valueOf(S));
            }
            else if("Auditor".equals(itemS))
            {
                S = 9000;
                textSueldo.setText(String.valueOf(S));
            }
            else if("Otro".equals(itemS))
            {
                S = 5000;
                textSueldo.setText(String.valueOf(S));
            }
            else if("Elija una opción".equals(itemS))
            {
                textSueldo.setText(String.valueOf(0));
            }
        
    }//GEN-LAST:event_comboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SueldoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SueldoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SueldoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SueldoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SueldoEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBono;
    private javax.swing.JCheckBox checkHExtra;
    private javax.swing.JCheckBox checkOBono;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane textDireccion;
    private javax.swing.JTextPane textNombre;
    private javax.swing.JTextPane textSueldo;
    private javax.swing.JTextPane textTotal;
    // End of variables declaration//GEN-END:variables
}
